apiVersion: v2
name: demo-java-helm
description: Chart de démonstration déployant l'application java-demo pour la formation CPiN
type: application

# Version du chart, à incrémenter à chaque modification (SemVer).
version: 0.1.0

# Version de l'application déployée, utilisée comme tag d'image par défaut.
appVersion: "0.0.1"

dependencies:
- name: postgres
  version: "0.11.1"
  repository: "oci://registry-1.docker.io/cloudpirates"
